---
- name: Example Playbook for custom filter plugins
  hosts: localhost

  tasks:
    - name: Fail test_template module
      test_template:
        name: 'fail me'
      ignore_errors: true

    - name: Pass test_template module as changed
      test_template:
        name: 'pass - changed'
        new: true

    - name: Pass test_template module
      test_template:
        name: 'pass - ok'